### ISSUE TITLE
Device cannot be reached

### ISSUE THREAD

**Issue by michalpol81** [bhuebschen/dreame-mower#15]
Rejestrator: custom_components.dreame_mower
Źródło: custom_components/dreame_mower/coordinator.py:331
integracja: Dreame Mower ([dokumentacja](https://github.com/bhuebschen/dreame-mower), [Problemy](https://github.com/bhuebschen/dreame-mower/issues))
Pierwsze zdarzenie: 20 marca 2025 23:12:14 (473 zdarzenia)
Ostatnio zalogowany: 09:38:23
Integration start failed: Traceback (most recent call last): File "/config/custom_components/dreame_mower/coordinator.py", line 325, in _async_update_data await self.hass.async_add_executor_job(self._device.update) File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/dreame_mower/dreame/device.py", line 2020, in update raise DeviceUpdateFailedException("Device cannot be reached") from None custom_components.dreame_mower.dreame.exceptions.DeviceUpdateFailedException: Device cannot be reached

**Comment by michalpol81** [comment]
Rejestrator: custom_components.dreame_mower.dreame.protocol
Źródło: custom_components/dreame_mower/dreame/protocol.py:351
integracja: Dreame Mower ([dokumentacja](https://github.com/bhuebschen/dreame-mower), [Problemy](https://github.com/bhuebschen/dreame-mower/issues))
Pierwsze zdarzenie: 20 marca 2025 23:12:13 (473 zdarzenia)
Ostatnio zalogowany: 09:38:22
Get Device OTC Info Retrying with fallback... ({'code': 0, 'success': True, 'data': {}, 'msg': '操作成功'})

**Comment by stas1000** [comment]
I am a bit confused with what is happening, is the alpha 0.03 version working again and safe to update to along with the HA core version to the March release or not? the last to issues were closed which seemed to have some back and forth going on about the code

**Comment by stas1000** [comment]
I just checked. It still doesn't work, had to roll back

**Comment by nyxdis** [comment]
This was fixed in PR #14 already, @bhuebschen please tag a new version so that we can upgrade

**Comment by michalpol81** [comment]
Still doesnt work, same error 

Integration start failed: Traceback (most recent call last): File "/config/custom_components/dreame_mower/coordinator.py", line 325, in _async_update_data await self.hass.async_add_executor_job(self._device.update) File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/dreame_mower/dreame/device.py", line 2020, in update raise DeviceUpdateFailedException("Device cannot be reached") from None custom_components.dreame_mower.dreame.exceptions.DeviceUpdateFailedException: Device cannot be reached

**Comment by nyxdis** [comment]
This was already fixed in #14, @bhuebschen please tag a new version

**Comment by michalpol81** [comment]
HACS provides version 0.0.3 alpha…which version will contain this fix?

**Comment by stas1000** [comment]
i would like to know the same thing. i have the exact same issue on the alpha 0.0.3

**Comment by milouzzzz** [comment]
0.0.3 doesn't contain the fixe. It's written as "successfuly merged" but it's not.
You can correct the 2 line manually. For me it worked.

**Comment by Bhafner2** [comment]
I have the same issu.
How to fix it?

**Comment by milouzzzz** [comment]
Make the corrections from here manually: https://github.com/bhuebschen/dreame-mower/pull/14/files
and it works

**Comment by stas1000** [comment]
This worked for me. Thanks

**Comment by larieu** [comment]
It worked for me, too
Thanks

**Comment by michalpol81** [comment]
Yep, It worked! Thanks!

**Comment by larieu** [comment]
It will be great if you do a pull request and add it to the main branch for other ppl, too.

**Comment by michalpol81** [comment]
I just copied entire file protocol.py from GitHub and restarted Ha.

**Comment by jonathansalgadoiglesias** [comment]
Después de corregir las dos líneas de código funcionaba sin problema, ahora ha dejado de funcionar de nuevo y no sé si fue por actualizar el robot o alguna de home assistant, hay algún fallo nuevo conocido??

**Comment by larieu** [comment]
I had already the modified version in my system and is not solving the issue.

I have tried to replace the old content with the new one ( which I have checked with a diff in linux and are 100% identical, the problem is not solved.

In logs I am able to see several different logs related Dreame integration.

1. `Detected that custom integration 'dreame_mower' sets option flow config_entry explicitly, which is deprecated at custom_components/dreame_mower/config_flow.py, line 63: self.config_entry = config_entry. This will stop working in Home Assistant 2025.12, please create a bug report at https://github.com/bhuebschen/dreame-mower/issues`
2. `Get Device OTC Info Retrying with fallback... ({'code': 0, 'success': True, 'data': {}, 'msg': '操作成功'})`
3. `Error while executing request: Read timed out. (read timeout=5): {"did":"-110198195","id":52,"data":{"did":"-110198195","id":52,"method":"get_properties","params":[{"did":"25","siid":4,"piid":21},{"did":"26","siid":4,"piid":22},{"did":"27","siid":4,"piid":23},{"did":"28","siid":4,"piid":24},{"did":"30","siid":4,"piid":26},{"did":"31","siid":4,"piid":27},{"did":"34","siid":4,"piid":30},{"did":"35","siid":4,"piid":31},{"did":"39","siid":4,"piid":35},{"did":"42","siid":4,"piid":38},{"did":"51","siid":4,"piid":47},{"did":"52","siid":4,"piid":48},{"did":"53","siid":4,"piid":49},{"did":"60","siid":4,"piid":56},{"did":"61","siid":4,"piid":57}]}}
Error while executing request: Read timed out. (read timeout=5): {"did":"-110198195","id":25,"data":{"did":"-110198195","id":25,"method":"get_properties","params":[{"did":"25","siid":4,"piid":21},{"did":"26","siid":4,"piid":22},{"did":"27","siid":4,"piid":23},{"did":"28","siid":4,"piid":24},{"did":"30","siid":4,"piid":26},{"did":"31","siid":4,"piid":27},{"did":"34","siid":4,"piid":30},{"did":"35","siid":4,"piid":31},{"did":"39","siid":4,"piid":35},{"did":"42","siid":4,"piid":38},{"did":"51","siid":4,"piid":47},{"did":"52","siid":4,"piid":48},{"did":"53","siid":4,"piid":49},{"did":"60","siid":4,"piid":56},{"did":"61","siid":4,"piid":57}]}}
Error while executing request: Read timed out. (read timeout=5): {"did":"-110198195","id":87,"data":{"did":"-110198195","id":87,"method":"get_properties","params":[{"did":"25","siid":4,"piid":21},{"did":"26","siid":4,"piid":22},{"did":"27","siid":4,"piid":23},{"did":"28","siid":4,"piid":24},{"did":"30","siid":4,"piid":26},{"did":"31","siid":4,"piid":27},{"did":"34","siid":4,"piid":30},{"did":"35","siid":4,"piid":31},{"did":"39","siid":4,"piid":35},{"did":"42","siid":4,"piid":38},{"did":"51","siid":4,"piid":47},{"did":"52","siid":4,"piid":48},{"did":"53","siid":4,"piid":49},{"did":"60","siid":4,"piid":56},{"did":"61","siid":4,"piid":57}]}}
Error while executing request: Read timed out. (read timeout=5): {"did":"-110198195","id":95,"data":{"did":"-110198195","id":95,"method":"get_properties","params":[{"did":"25","siid":4,"piid":21},{"did":"26","siid":4,"piid":22},{"did":"27","siid":4,"piid":23},{"did":"28","siid":4,"piid":24},{"did":"30","siid":4,"piid":26},{"did":"31","siid":4,"piid":27},{"did":"34","siid":4,"piid":30},{"did":"35","siid":4,"piid":31},{"did":"39","siid":4,"piid":35},{"did":"42","siid":4,"piid":38},{"did":"51","siid":4,"piid":47},{"did":"52","siid":4,"piid":48},{"did":"53","siid":4,"piid":49},{"did":"60","siid":4,"piid":56},{"did":"61","siid":4,"piid":57}]}}`
4.`Integration start failed: Traceback (most recent call last): File "/config/custom_components/dreame_mower/coordinator.py", line 325, in _async_update_data await self.hass.async_add_executor_job(self._device.update) File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/dreame_mower/dreame/device.py", line 2017, in update self.connect_device() ~~~~~~~~~~~~~~~~~~~^^ File "/config/custom_components/dreame_mower/dreame/device.py", line 1351, in connect_device self._request_properties() ~~~~~~~~~~~~~~~~~~~~~~~~^^ File "/config/custom_components/dreame_mower/dreame/device.py", line 525, in _request_properties result = self._protocol.get_properties(props[:15]) File "/config/custom_components/dreame_mower/dreame/protocol.py", line 1246, in get_properties return self.send("get_properties", parameters=parameters, retry_count=retry_count) ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/dreame_mower/dreame/protocol.py", line 1238, in send raise DeviceException("Unable to discover the device over cloud") from None custom_components.dreame_mower.dreame.exceptions.DeviceException: Unable to discover the device over cloud `

the official app is working fine

**Comment by bhuebschen** [comment]
please try [0.0.4-alpha](https://github.com/bhuebschen/dreame-mower/releases/tag/v0.0.4-alpha)

**Comment by fraschizzato** [comment]
In my environment, paho-mqtt library version 1.6.1, the solution was to remove from protocol.py:
        `mqtt_client.CallbackAPIVersion.VERSION1,`
in
#https://github.com/fraschizzato/dreame-mower/commit/fb4b3121f5685b5f899d3dbd36943bd0b13d6741


for me that had solved the issue, found in hass log as:
`Connect failed. error: module 'paho.mqtt.client' has no attribute 'CallbackAPIVersion'`

also an on-the-fly mod to protocol.py and an hass restart solves the issue

**Comment by larieu** [comment]
> In my environment, paho-mqtt library version 1.6.1, the solution was to remove from protocol.py: `mqtt_client.CallbackAPIVersion.VERSION1,` in #[fraschizzato@fb4b312](https://github.com/fraschizzato/dreame-mower/commit/fb4b3121f5685b5f899d3dbd36943bd0b13d6741)
> 
> for me that had solved the issue, found in hass log as: `Connect failed. error: module 'paho.mqtt.client' has no attribute 'CallbackAPIVersion'`
> 
> also an on-the-fly mod to protocol.py and an hass restart solves the issue

this is not solving my issue
after deleting and taking it from scratch I am stuck with the 

[issue17](https://github.com/bhuebschen/dreame-mower/issues/17)

**Comment by nyxdis** [comment]
> please try [0.0.4-alpha](https://github.com/bhuebschen/dreame-mower/releases/tag/v0.0.4-alpha)

0.0.4-alpha fixes the original issue for me. #17 is a different issue.
